org: parislht
service: microservicio-compras

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::418047659300:role/LabRole
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${sls:stage}-t_compras
    VALIDAR_TOKEN_FUNC: ${sls:stage}-ValidarTokenAcceso

functions:
  registrarCompra:
    handler: RegistrarCompra.lambda_handler
    events:
      - http:
          path: /compras/registrar
          method: post
          cors: true
          integration: lambda

  listarCompra:
    handler: ListarCompra.lambda_handler
    events:
      - http:
          path: /compras/listar
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaCompras:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: username#compra_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: username#compra_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
